# Use official OpenJDK image from Docker Hub as the base image
FROM openjdk:11-jre-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the built jar file (assuming you built it using Maven)
COPY target/*.jar app.jar

# Expose the port on which the Spring Boot app will run
EXPOSE 8080

# Run the Spring Boot app
CMD ["java", "-jar", "app.jar"]
